### ISSUE TITLE
import conflicts due to all directories being added to sys.path

### ISSUE THREAD

**Issue by manishshettym** [r2e-project/r2e-test-server#12]
Commit: https://github.com/r2e-project/r2e-test-server/pull/9

```diff
-            if self.repo_path not in sys.path:
-                sys.path.insert(0, self.repo_path)
+            all_repo_to_file_paths: list[str] = [self.repo_path]
+            curr_path = os.path.dirname(self.file_path)
+            while curr_path != self.repo_path:
+                all_repo_to_file_paths.append(curr_path)
+                curr_path = os.path.dirname(curr_path)
+
+            for repo_to_file_path in all_repo_to_file_paths:
+                if repo_to_file_path not in sys.path:
+                    sys.path.insert(0, repo_to_file_path)
```

The above commit adds all directories in the path to the fut_module to sys.path. I imagine this was made to handle monorepo structure - one repo w/ multiple subrepo (each being a package)

**Assumption**: Adding all directories to sys w/o knowing the repo assumes that each dir can be a separate package.

**Consequence:** consider a repo like google/jax. It has custom stuff like `jax/typing.py` and `jax/_src/numpy/...` which when pushed to sys end up causing import conflicts with actual libraries with the same name. See error message below for an example.

**Comment by manishshettym** [comment]
> Error: Traceback (most recent call last):
>   ...
>   File "/home/manishs/Projects/r2e-test-server/r2e_test_server/testing/r2e_testprogram.py", line 279, in import_module_dynamic
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in callwith_frames_removed
>   File "/home/manishs/buckets/local_repoeval_bucket/repos/LOCAL_jax/jax/_src/numpy/setops.py", line 22, in <module>
>     import numpy as np
>   File "/home/manishs/buckets/local_repoevalbucket/repos/LOCALjax/jax/numpy/init.py", line 18, in <module>
>     from jax.numpy import fft as fft
>   File "/home/manishs/buckets/local_repoeval_bucket/repos/LOCAL_jax/jax/init.py", line 25, in <module>
>     from jax._src.cloud_tpu_init import cloud_tpu_init as cloudtpu_init
>   File "/home/manishs/buckets/local_repoevalbucket/repos/LOCALjax/jax/_src/cloud_tpu_init.py", line 17, in <module>
>     from jax._src import config
>   File "/home/manishs/buckets/local_repoeval_bucket/repos/LOCAL_jax/jax/_src/config.py", line 27, in <module>
>     from jax._src import lib
>   File "/home/manishs/buckets/local_repoevalbucket/repos/LOCALjax/jax/_src/lib/init.py", line 87, in <module>
>     import jaxlib.xla_client as xla_client
>   File "/home/manishs/.cache/pypoetry/virtualenvs/r2e-JhMPySkJ-py3.11/lib/python3.11/site-packages/jaxlib/xla_client.py", line 30, in <module>
>     import ml_dtypes
>   File "/home/manishs/.cache/pypoetry/virtualenvs/r2e-JhMPySkJ-py3.11/lib/python3.11/site-packages/ml_dtypes/init.py", line 32, in <module>
>     from ml_dtypes._finfo import finfo
>   File "/home/manishs/.cache/pypoetry/virtualenvs/r2e-JhMPySkJ-py3.11/lib/python3.11/site-packages/ml_dtypes/_finfo.py", line 19, in <module>
>     from ml_dtypes._ml_dtypes_ext import bfloat16
> ImportError: numpy.core.umath failed to import

> Small Error: ImportError('numpy.core.umath failed to import')`
